### ISSUE TITLE
Compatibility with Linak DPG1C

### ISSUE THREAD

**Issue by darkkatarsis** [sroebert/ikea-desk-control#2]
Hi, I'm trying to start the APP from my raspberry zero W and connect to a Linak desk with the DPG1C module but im stuck on "start scanning". Can you show me the direction where the problem may be?

<img width="959" alt="Screenshot 2020-06-06 at 14 30 23" src="https://user-images.githubusercontent.com/24244919/83944252-476dca80-a802-11ea-9687-389da21454d2.png">

<img width="635" alt="Screenshot 2020-06-06 at 15 14 25" src="https://user-images.githubusercontent.com/24244919/83945079-6d966900-a808-11ea-91f7-dd3429c80aba.png">

**Comment by rmervine** [comment]
@darkkatarsis , I saw you closed this issue out and I'm running into the same problem. Have you found what's causing this not to be discovered?

**Comment by darkkatarsis** [comment]
No, I just let it go.

**Comment by rmervine** [comment]
Ah ok. I actually did figure out the issue. The controller was paired in bluetoothctl. I was then able to get it detected. And I can get the status in MQTT, just not able to control it.
